on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - closed
    paths:
      - '**/*.cs'
      - '**/*.csproj'
  push:
    branches:
      - master
      - develop
    paths:
      - '**/*.cs'
      - '**/*.csproj'

env:
  GIT_BRANCH: 'master'

jobs:
  determine:
    if: github.event.pull_request.merged == true # Only create a new tag when a PR is merged
    runs-on: ubuntu-latest

    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
          versionSpec: '5.x'

    - name: Check out Code 
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml
    
    - name: Print Version
      run: echo ${{ steps.gitversion.outputs.FullSemVer }}
