on:
  push:
    tags:
      - "*"

jobs:
  determine:
    runs-on: ubuntu-latest

    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
          versionSpec: '5.x'

    - name: Check out Code 
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
          ref: master

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml
    
    - name: Print Version
      run: echo ${{ steps.gitversion.outputs.FullSemVer }}
